import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import dotenv from 'dotenv';

dotenv.config();

let doc: GoogleSpreadsheet | null = null;

const ENCODED_EMAIL = "ZmlyZWJhc2UtYWRtaW5zZGstZmJzdmNAYWVnaXN2YXVsdC1jcm0uaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20=";
const ENCODED_PRIVATE_KEY = "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzRxY3JqOTFTczRHWTkKd00yWFVBMWlmeW5weGhBRnNzVUlDV3gzZmYrK3QxRmtiTWlTUVRtaWM5Y2F1ZnloTUI3a1pzMDJncXljNFRZRQpMZTlWaExhWXA1OFl4MmY3Tm9wVW0wdVcwOU10VEpaMmtLbnZORjNlem5FMCtaZzlpREFoZGFCc2ZPcnVRUEdxCi9tUkxFTktySmdLQU1WbTdXRDhOeTcxMGVIaDBOZG9DRzhmckg0NVc1dWVJVW1iN0VyZC8vM2V1RUpvcUhoV3UKSCt6Tk43WloyaldtbmZYdktGaG41T3JBRE8yUnk3ZjBpNlB1eFVqa2ZjZ010bklDVHpNM2MwZW1hclpBQlhMSAo2TFM0a2V1NGJnSUNMRWZ4VjByYUpxMGN3cVhEM0d3SG9jRktYQWdBbkgwN2c4QXJIRG9OY05NZG13dVZ1dHFSCmlFNVhqSDViQWdNQkFBRUNnZ0VBS3lmak5xdVNxbVEzQUsrU1hJNWswbVFOazRpcUxlcTlpVWRLaGhKNE5rWDUKUzVMd3ZOMXBic0hMdjM4L3Z4dlQzR1Q2Q0ljNWQrQmFFMWY0MnUrTkROZi9vbmJYb2luNDRoVDQ4V0xIczRwMgpqM2IzZitPcEhHejZuL3JFelh5S1l3ZHVXbXhIS3k4YVMyL3dXR3F5RVRWczJEQ3dXOHdmMEVXUkhTc2FXMjNrCmJ1MEhNZzVOWUx4WkgwWVJxemprUUFqajNqK3BZdm9QczhtUHgyQ1BqTTIrcFJreVdiRTVmVWU3cHBjei9pdkMKcis4UXl1bUw3S2VWRTBreStlZTFpUFJOOGp6VmtNcVhqVTF0ZWIwQ2gwNlJ6SXhrekJvOU8rREQzam8wY1RoSApzUDVkVG5SOUpOTGRqTExTcDlyZENnc1hRMjJkNG1xdE1lVHVWei9Dd1FLQmdRRHNSSUJoZWh0UDIyR1RUZzZjCm1tMXRiWFdENEJxc2FnRkthTFZTSTE1bW55UWFkK21TaHMybmwwQmFIZzA5L0w1YVg1V2cwZ1BCdlhNa1Q4S1YKRjJUcEdmNnBPMTdEb1hSamZxbkJKRmlTN3pCd1ZrdGxRY0h0Uk4xazBSYm9iNW1ES2NrMjJ0OWkxUXBRQ0o3awppVDgyMjlsdlNvd096SFl0My9GMlVZdHBzd0tCZ1FESUZmZ1kxWnoxSjdmNStiRjlNNXQ0VXFNR215Z0M5NTB2CkR6MTdiTTA2WVBkTldHMUNxbXJSTXdtamxPbnA3U3pvaEs5bDFDejlEYlhtdjdqOWJQbnhsVzlzR1Nwd09BRG8KWUZ6S2FJWXBsRFFmb0VaOHlTT3ZMbjNuYjFhbXZaNG41SDlRUVZNaUNoTXNWa0Yzb25DTnRXNzhXa3hHUTBaclhSeWZobmgwdVFLQmdDL09xSitRd3FnRS94aDhhZTU4UFBvd2ROL3JYOXBWVk0rR29uSHRZRE9wcmZlQkhnMGQKSTgzdWlBSDBKTC9QUFlFeDZDZnpkdmtqNllHR2Rod084TWRPRUQ2VUdkZkIrcmdMTURRNXM0Wi95YkJoZGI0VwpjVFFlaENIYlFTUmxPSTNXemJWQTBvVEFFT2NpNTJ2YzdhS2ZGNzh5T1diaExtU1g5TmI1SnhtTEFvR0FTOFVXCkNNR01DTUtieHd3cGpKSW9nKzQzVWw4YlRkUmJMK0VEbFdQa2JBRWdaYWZnNkdnRXYyZ21kRTRHTHRIa09jRlYKY3FoZ3lRdVNJT25sc2dLOHZDR3M2akMxZzMyUnltNERkWnNUZzFkZVRjT3lMYnMxeWpjKzhvK1ZMdHVMc3V1eQowcitLTGMvRzV2bGJIV1RrWHFXZ2UrdnVDb1diZXpqdGgvT3lWZkVDZ1lFQXo2VHpob21LUGNYMDlMMHVvYkNXCnBCMmprZi9vWEFTK2Q5QmRjbG5PQUhzdTV3eGExa1J5aGIzY0RRakphazF4SWtVMitOM21BaHpXY092eENXZUUKc3VWSzhTWmk5Wi93MEt6b3ZxVmF3YnJEQ3o3M3p3OVg0MjdMc0s1VHhZQ1lkbitUQlFTek1aT0MwZHZYOXUrcAo1T0M4a2RsRTdLRVM1SlpFMWZZeExudz0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=";

function decodeBase64(encoded: string): string {
  return Buffer.from(encoded, 'base64').toString('utf8');
}

/**
 * Initializes and authenticates the Google Sheets API client using a Service Account.
 * Environment variables required:
 * GOOGLE_SERVICE_ACCOUNT_EMAIL
 * GOOGLE_PRIVATE_KEY
 * GOOGLE_SHEET_ID
 */
export async function getSheetsDoc() {
  if (doc) return doc;

  const email = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || decodeBase64(ENCODED_EMAIL);
  // Handle newlines correctly
  const rawKey = process.env.GOOGLE_PRIVATE_KEY || decodeBase64(ENCODED_PRIVATE_KEY);
  const privateKey = rawKey.replace(/\\n/g, '\n');
  const sheetId = process.env.GOOGLE_SHEET_ID;

  if (!email || !privateKey || !sheetId) {
    throw new Error('Google Sheets API credentials or Sheet ID are not fully configured.');
  }

  const auth = new JWT({
    email,
    key: privateKey,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });

  const newDoc = new GoogleSpreadsheet(sheetId, auth);
  await newDoc.loadInfo();
  doc = newDoc;
  return doc;
}
